name: Tagger

on:
  pull_request:
    types:
      - closed

jobs:
  check:
    name: Check
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.latest_version.outputs.latest_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve latest version
        id: latest_version
        run: |
          latest_version=$(echo ${{ github.head_ref }} | sed 's#release/newver-##' | sed 's#-rc#.#')
          echo "latest_version=${latest_version}" >> $GITHUB_OUTPUT

      - name: Output latest versions
        run: |
          echo "The latest version of the merged pull request is: ${{ steps.latest_version.outputs.latest_version }}"

  tagging:
    name: Tagging
    runs-on: ubuntu-latest
    needs: ['check']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.58.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TAGGING }} # To trigger the builder workflow, a personal access token is required.
          WITH_V: false
          CUSTOM_TAG: '${{ needs.check.outputs.latest_version }}'
